### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by fgadaleta** [antholeole/actix-sockets#2]
Seems to run in timeout

**Comment by fgadaleta** [comment]
```
websocat ws://127.0.0.1:8888
websocat: WebSocketError: Received unexpected status code (404 Not Found)
websocat: error running
```

**Comment by antholeole** [comment]
you have to connect to a lobby id, like `localhost:8080/c05554ae-b4ee-4976-ac05-97aaf3c98a23`. Lobby ID must be a valid UUID. only other people in your lobby can see your messages.

I added quickstart in readme.

For me, it's:

```
wscat -c localhost:8080/c05554ae-b4ee-4976-ac05-97aaf3c98a23
```

for you (assuming you intentionally changed the port to 8888 from the default 8080 and are using websocat):

```
websocat ws://127.0.0.1:8080/c05554ae-b4ee-4976-ac05-97aaf3c98a23
```

**Comment by fgadaleta** [comment]
ah
thank you didn't see that uuid...
