### ISSUE TITLE
Is that possible to share how to send a PING and get PONG response? (Codes and Explaination)

### ISSUE THREAD

**Issue by edwardchang0112** [antholeole/actix-sockets#4]
Since I am trying to use actix websocket to make communication, I found this repo that is really useful!!!
However I just cannot know run it up, for instance how to send a PING and get PONG response (the command like curl -X GET http://127.0.0.1:8080/ws/...) what commands should I use?

**Comment by antholeole** [comment]
Hi there, sorry! Missed this issue. Ping pong on websockets works a little differently then http. if you have [wscat](https://github.com/websockets/wscat) installed, something like this would work:

```
wscat -c localhost:8080/c05554ae-b4ee-4976-ac05-97aaf3c98a23 -P  --slash
```

the -P means that we explicitly show pings, and --slash enables slash commands.

then, enter `/ping` and you should see a pong like this:

```
< Received pong
```

also, you should see explicit pings coming to the client: 

```
< Received ping
< Received ping
< Received ping
< Received ping
```

let me know if this helps.

**Comment by antholeole** [comment]
closing until further update
